#! /bin/bash

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
echo "Migrating database ..."
RAILS_ENV=production bundle exec rake db:migrate
echo "precomile in production ..."
RAILS_ENV=production bundle exec rake assets:precompile

STORED_ASSETS="${OPENSHIFT_DATA_DIR}/assets/advertises/pictures"
LIVE_ASSETS="${OPENSHIFT_REPO_DIR}/public/assets"

# Ensure our stored assets directory exists
if [ ! -d "${STORED_ASSETS}" ]; then
    echo " Creating permanent assets directory"
    mkdir -p "${STORED_ASSETS}"
fi

# Create symlink to stored assets unless we're uploading our own assets
if [ ! -d "${LIVE_ASSETS}" ]; then
    echo " WARNING: Assets not compiled"
else
    echo " Restoring stored assets"
    ln -sf "${STORED_ASSETS}" "${LIVE_ASSETS}/advertises/pictures"
fi
popd > /dev/null
